# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d39fed56fd99ad1659174d0a9a22b14be1ee05d790672f736d3f4375b9cf328ed7d47121b52f829e9a1608a2d2a6c239617fcd27f4c4a4e25285372197d4987d

test:
  secret_key_base: c2a09c05ad220429e8ef706ee5fdd208080b5a9d191714d65cdde63adb5cbe27a7902054536d90f666750e7aa760ad454be86fa160d9cb29e23c9bb94d344da9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
